/*
 * Project Euler  <https://projecteuler.net>
 *
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

using System;


class Program {
	static void Main() {
		int MAXFIB = 4000000;
		int fib1 = 1;
		int fib2 = 2;
		int temp = 0;
		int total = 2;

		while (temp < MAXFIB) {
			temp = fib1 + fib2;
			if (temp % 2 == 0) {
				total += temp;
			}
			fib1 = fib2;
			fib2 = temp;
		}

		Console.WriteLine("The total is: {0}", total);




	}
}
